// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_F4jl6Nu0iUb2gVFtOhcWnLSHtNcDIHM',
    appId: '1:490137200342:web:383dfe2c4b40ac13210b77',
    messagingSenderId: '490137200342',
    projectId: 'asset-tracker-3cc21',
    authDomain: 'asset-tracker-3cc21.firebaseapp.com',
    storageBucket: 'asset-tracker-3cc21.firebasestorage.app',
    measurementId: 'G-884MJ1RRDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbzJ2D7gAvJjwbiG0bwp8yO-TPqqQWb0',
    appId: '1:490137200342:android:52806d2e5cffbb33210b77',
    messagingSenderId: '490137200342',
    projectId: 'asset-tracker-3cc21',
    storageBucket: 'asset-tracker-3cc21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_5T4yr-6fE_sHhqkp-Zw4z4ZRaF8PblA',
    appId: '1:490137200342:ios:32fa08ba5eeb1236210b77',
    messagingSenderId: '490137200342',
    projectId: 'asset-tracker-3cc21',
    storageBucket: 'asset-tracker-3cc21.firebasestorage.app',
    iosBundleId: 'com.example.assetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_5T4yr-6fE_sHhqkp-Zw4z4ZRaF8PblA',
    appId: '1:490137200342:ios:32fa08ba5eeb1236210b77',
    messagingSenderId: '490137200342',
    projectId: 'asset-tracker-3cc21',
    storageBucket: 'asset-tracker-3cc21.firebasestorage.app',
    iosBundleId: 'com.example.assetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_F4jl6Nu0iUb2gVFtOhcWnLSHtNcDIHM',
    appId: '1:490137200342:web:6c77bd6fbb179f85210b77',
    messagingSenderId: '490137200342',
    projectId: 'asset-tracker-3cc21',
    authDomain: 'asset-tracker-3cc21.firebaseapp.com',
    storageBucket: 'asset-tracker-3cc21.firebasestorage.app',
    measurementId: 'G-SZ97T6LQJX',
  );
}
