import 'package:asset_tracker/i18n/strings.g.dart';

class CurrencyNames {
  static Map<String, String> names = {
    'KULCEALTIN': t.currency.names.KULCEALTIN,
    'ALTIN': t.currency.names.ALTIN,
    'CEYREK_ESKI': t.currency.names.CEYREK_ESKI,
    'CEYREK_YENI': t.currency.names.CEYREK_YENI,
    'YARIM_ESKI': t.currency.names.YARIM_ESKI,
    'YARIM_YENI': t.currency.names.YARIM_YENI,
    'TEK_ESKI': t.currency.names.TEK_ESKI,
    'TEK_YENI': t.currency.names.TEK_YENI,
    'ATA_ESKI': t.currency.names.ATA_ESKI,
    'ATA_YENI': t.currency.names.ATA_YENI,
    'AUDTRY': t.currency.names.AUDTRY,
    'AYAR22': t.currency.names.AYAR22,
    'AYAR24': t.currency.names.AYAR24,
    'AYAR26': t.currency.names.AYAR26,
    'AYAR28': t.currency.names.AYAR28,
    'AYAR30': t.currency.names.AYAR30,
    'USDTRY': t.currency.names.USDTRY,
    'EURTRY': t.currency.names.EURTRY,
    'GBPTRY': t.currency.names.GBPTRY,
    'CHFTRY': t.currency.names.CHFTRY,
    'SARTRY': t.currency.names.SARTRY,
    'JPYTRY': t.currency.names.JPYTRY,
    'SEKTRY': t.currency.names.SEKTRY,
    'DKKTRY': t.currency.names.DKKTRY,
    'NOKTRY': t.currency.names.NOKTRY,
    'CADTRY': t.currency.names.CADTRY,
    'USDCAD': t.currency.names.USDCAD,
    'XAUXAG': t.currency.names.XAUXAG,
    'USDPURE': t.currency.names.USDPURE,
    'USDKG': t.currency.names.USDKG,
    'EURKG': t.currency.names.EURKG,
    'GBPKG': t.currency.names.GBPKG,
    'GBPUSD': t.currency.names.GBPUSD,
    'GREMESE_ESKI': t.currency.names.GREMESE_ESKI,
    'GREMESE_YENI': t.currency.names.GREMESE_YENI,
    'ATA5_ESKI': t.currency.names.ATA5_ESKI,
    'ATA5_YENI': t.currency.names.ATA5_YENI,
    'GUMUSTRY': t.currency.names.GUMUSTRY,
    'XPTUSD': t.currency.names.XPTUSD,
    'EURUSD': t.currency.names.EURUSD,
    'USDJPY': t.currency.names.USDJPY,
    'XAGUSD': t.currency.names.XAGUSD,
    'GUMUSUSD': t.currency.names.GUMUSUSD,
    'XPDUSD': t.currency.names.XPDUSD,
    'XAUUSD': t.currency.names.XAUUSD,
    'USDSAR': t.currency.names.USDSAR,
    'AUDUSD': t.currency.names.AUDUSD,
    'USDCHF': t.currency.names.USDCHF,
    'USDCNY': t.currency.names.USDCNY,
    'USDMXN': t.currency.names.USDMXN,
    'USDPHP': t.currency.names.USDPHP,
    'USDMYR': t.currency.names.USDMYR,
  };
}
