class CurrencyNames {
  static const Map<String, String> names = {
    'KULCEALTIN': 'Külçe Altın',
    'ALTIN': 'Altın',
    'CEYREK_ESKI': 'Çeyrek Altın(Eski)',
    'CEYREK_YENI': 'Çeyrek Altın(Yeni)',
    'YARIM_ESKI': 'Yarım Altın(Eski)',
    'YARIM_YENI': 'Yarım Altın(Yeni)',
    'TEK_ESKI': 'Tek Altın(Eski)',
    'TEK_YENI': 'Tek Altın(Yeni)',
    'ATA_ESKI': 'Ata Altın(Eski)',
    'ATA_YENI': 'Ata Altın(Yeni)',
    'AUDTRY': 'Avustralya Doları/TRY',
    'AYAR22': '22 Ayar Altın',
    'AYAR24': '24 Ayar Altın',
    'AYAR26': '26 Ayar Altın',
    'AYAR28': '28 Ayar Altın',
    'AYAR30': '30 Ayar Altın',
    'USDTRY': 'Dolar/TRY',
    'EURTRY': 'Euro/TRY',
    'GBPTRY': 'Sterlin/TRY',
    'CHFTRY': 'Frang/TRY',
    'SARTRY': 'Riyal/TRY',
    'JPYTRY': 'Yen/TRY',
    'SEKTRY': 'Sveç Kron/TRY',
    'DKKTRY': 'Dansk Kron/TRY',
    'NOKTRY': 'Norveç Kron/TRY',
    'CADTRY': 'Kanada Doları/TRY',
    'USDCAD': 'Dolar/Kanada Doları',
    'XAUXAG': 'Altın/Gümüş',
    'USDPURE': 'Dolar',
    'USDKG': 'Dolar/Kg',
    'EURKG': 'Euro/Kg',
    'GBPKG': 'Sterlin/Kg',
    'GBPUSD': 'Sterlin/Dolar',
    'GREMESE_ESKI': 'Gremese Altın (Eski)',
    'GREMESE_YENI': 'Gremese Altın (Yeni)',
    'ATA5_ESKI': 'Ata 5 (Eski) Altın',
    'ATA5_YENI': 'Ata 5 (Yeni) Altın',
    'GUMUSTRY': 'Gümüş/TRY',
    'XPTUSD': 'Palladyum/Dolar',
    'EURUSD': 'Euro/Dolar',
    'USDJPY': 'Dolar/Yen',
    'XAGUSD': 'Gümüş/Dolar',
    'GUMUSUSD': 'Gümüş/Dolar',
    'XPDUSD': 'Platin/Dolar',
    'XAUUSD': 'Altın/Dolar',
    'USDSAR': 'Dolar/Riyal',
    'AUDUSD': 'Avustralya Doları/Dolar',
    'USDCHF': 'Dolar/Frang',
    'USDCNY': 'Dolar/Çin Yuan',
    'USDMXN': 'Dolar/Meksika Peso',
    'USDPHP': 'Dolar/Filipin Peso',
    'USDMYR': 'Dolar/Malezya Ringgit',
  };
}
